"""Amazon platform template — structures content for Amazon marketplace listing."""

from src.models.content import LocalizedContent


AMAZON_TEMPLATE = """
## Amazon Listing Content

### Title
{title}

### Bullet Points
{bullets}

### Product Description
{description}

### Brand Story
{brand_story}

### Backend Search Terms
{search_terms}

### SEO Metadata
- Primary Keyword: {primary_keyword}
- Secondary Keywords: {secondary_keywords}

---
*Locale: {locale} | Generated by MIMO Content Factory*
"""


def format_amazon_listing(content: LocalizedContent) -> str:
    """Format localized content into an Amazon listing template."""
    bullets = "\n".join(f"- {b}" for b in content.bullets) if content.bullets else "- N/A"
    secondary_kw = ", ".join(content.seo.secondary_keywords) if content.seo.secondary_keywords else "N/A"

    return AMAZON_TEMPLATE.format(
        title=content.title,
        bullets=bullets,
        description=content.description,
        brand_story=content.brand_story or content.description,
        search_terms=content.amazon_search_terms or content.seo.primary_keyword,
        primary_keyword=content.seo.primary_keyword,
        secondary_keywords=secondary_kw,
        locale=content.locale,
    ).strip()


def amazon_schema(content: LocalizedContent) -> dict:
    """Return a structured Amazon-compatible data dict for API integration."""
    return {
        "title": content.title,
        "bullet_points": content.bullets[:5],
        "description": content.description,
        "search_terms": (content.amazon_search_terms or content.seo.primary_keyword)[:500],
        "locale": content.locale,
        "brand_story": content.brand_story,
        "meta_title": content.seo.meta_title,
        "meta_description": content.seo.meta_description,
    }
