"""Shopify platform template — structures content for independent store product page."""

from src.models.content import LocalizedContent


SHOPIFY_TEMPLATE = """
## Shopify Product Page Content

### Product Title
{title}

### Product Description
{description}

### Key Features
{bullets}

### Brand Story
{brand_story}

### SEO
- Page Title: {meta_title}
- Meta Description: {meta_description}
- URL Handle: {url_handle}

### Hashtags for Social Sharing
{hashtags}

---
*Locale: {locale} | Generated by Marketing Content Factory*
"""


def format_shopify_page(content: LocalizedContent) -> str:
    """Format localized content into a Shopify product page template."""
    bullets = "\n".join(f"- {b}" for b in content.bullets) if content.bullets else "- N/A"
    hashtags = " ".join(content.hashtags) if content.hashtags else ""

    if content.seo.meta_title:
        meta_title = content.seo.meta_title
    else:
        meta_title = content.title[:70]

    return SHOPIFY_TEMPLATE.format(
        title=content.title,
        description=content.description,
        bullets=bullets,
        brand_story=content.brand_story or content.description,
        meta_title=meta_title,
        meta_description=content.shopify_meta or content.seo.meta_description or content.description[:160],
        url_handle=content.title.lower().replace(" ", "-").replace("/", "-")[:100],
        hashtags=hashtags,
        locale=content.locale,
    ).strip()


def shopify_schema(content: LocalizedContent) -> dict:
    """Return a structured Shopify-compatible data dict for API integration."""
    return {
        "title": content.title[:70],
        "body_html": f"<p>{content.description}</p>",
        "metafields_global_title_tag": content.seo.meta_title or content.title[:70],
        "metafields_global_description_tag": content.shopify_meta or content.seo.meta_description or content.description[:160],
        "handle": content.title.lower().replace(" ", "-").replace("/", "-")[:100],
        "locale": content.locale,
        "tags": ",".join(content.hashtags) if content.hashtags else "",
    }
