"""TikTok / Instagram platform template — social media script and caption."""

from src.models.content import LocalizedContent


TIKTOK_TEMPLATE = """
## TikTok / Instagram Content

### Video Script
{script}

### Caption
{caption}

### Hashtags
{hashtags}

### SEO / Discoverability
- Primary Keyword: {primary_keyword}
- Secondary Keywords: {secondary_keywords}

---
*Locale: {locale} | Platform: TikTok/Instagram | Generated by MIMO Content Factory*
"""


def format_tiktok_content(content: LocalizedContent) -> str:
    """Format localized content into a TikTok/Instagram social media template."""
    hashtags = " ".join(content.hashtags) if content.hashtags else ""
    secondary_kw = ", ".join(content.seo.secondary_keywords) if content.seo.secondary_keywords else "N/A"

    return TIKTOK_TEMPLATE.format(
        script=content.tiktok_script or "No script generated",
        caption=content.tiktok_caption or content.description[:2200],
        hashtags=hashtags,
        primary_keyword=content.seo.primary_keyword,
        secondary_keywords=secondary_kw,
        locale=content.locale,
    ).strip()


def tiktok_schema(content: LocalizedContent) -> dict:
    """Return a structured TikTok/Instagram-compatible data dict for API integration."""
    return {
        "script": content.tiktok_script or "",
        "caption": content.tiktok_caption or content.description[:2200],
        "hashtags": content.hashtags,
        "primary_keyword": content.seo.primary_keyword,
        "locale": content.locale,
        "platform": "tiktok",
    }
