"""Content asset data models for the content factory pipeline."""

from datetime import datetime
from enum import Enum
from pydantic import BaseModel, Field


class ContentStatus(str, Enum):
    DRAFT = "draft"
    LOCALIZED = "localized"
    REVIEWED = "reviewed"
    APPROVED = "approved"
    REJECTED = "rejected"
    PUBLISHED = "published"
    FAILED = "failed"


class BrandStoryline(BaseModel):
    """Master brand storyline generated by the CopywriterAgent (English canonical)."""
    product_name: str = Field(..., description="Canonical product name in English")
    brand_voice: str = Field(..., description="Brand voice description")
    headlines: list[str] = Field(..., description="3-5 headline variants")
    story_paragraph: str = Field(..., description="Brand story paragraph (emotional hook)")
    usp_angles: list[str] = Field(..., description="Unique selling proposition angles")
    bullet_points: list[str] = Field(..., description="5 key feature/benefit bullets")
    call_to_action: str = Field(..., description="Call to action text")
    tone_notes: str = Field(default="", description="Tone guidelines for localizers")


class SEOMetadata(BaseModel):
    """SEO metadata for a localized piece of content."""
    primary_keyword: str = Field(..., description="Primary target keyword")
    secondary_keywords: list[str] = Field(default_factory=list, description="Secondary/long-tail keywords")
    search_terms: list[str] = Field(default_factory=list, description="Backend search terms")
    hashtags: list[str] = Field(default_factory=list, description="Social media hashtags")
    meta_title: str = Field(default="", description="SEO meta title")
    meta_description: str = Field(default="", description="SEO meta description")


class LocalizedContent(BaseModel):
    """Content localized for a specific language and platform."""
    locale: str = Field(..., description="Target locale code (fr, de, es, ja, ko, pt, it, ar)")
    platform: str = Field(..., description="Target platform: amazon, shopify, tiktok")
    status: ContentStatus = Field(default=ContentStatus.DRAFT)

    title: str = Field(..., description="Localized product title")
    description: str = Field(..., description="Localized product description")
    bullets: list[str] = Field(default_factory=list, description="Localized bullet points")
    brand_story: str = Field(default="", description="Localized brand story")

    # Platform-specific
    amazon_search_terms: str = Field(default="", description="Amazon backend search terms")
    tiktok_script: str = Field(default="", description="Short video script for TikTok")
    tiktok_caption: str = Field(default="", description="TikTok post caption")
    shopify_meta: str = Field(default="", description="Shopify meta description")

    seo: SEOMetadata = Field(default_factory=lambda: SEOMetadata(primary_keyword=""))
    hashtags: list[str] = Field(default_factory=list)

    created_at: str = Field(default_factory=lambda: datetime.utcnow().isoformat())
    source_storyline_hash: str = Field(default="", description="Hash of source storyline for traceability")


class ReviewIssue(BaseModel):
    """A single issue found during cultural QA review."""
    severity: str = Field(..., description="error, warning, or suggestion")
    category: str = Field(..., description="taboo, sensitivity, compliance, tone, seo")
    description: str = Field(..., description="Issue description")
    location: str = Field(default="", description="Where in the content the issue was found")
    suggestion: str = Field(default="", description="Suggested fix")


class ReviewResult(BaseModel):
    """Result from the ReviewAgent cultural QA check."""
    locale: str
    platform: str
    passed: bool = Field(..., description="Whether the content passed review")
    issues: list[ReviewIssue] = Field(default_factory=list)
    risk_score: float = Field(default=0.0, ge=0.0, le=1.0, description="Cultural risk score (0=clean, 1=high risk)")
    reviewer_notes: str = Field(default="")
    reviewed_at: str = Field(default_factory=lambda: datetime.utcnow().isoformat())


class PublishResult(BaseModel):
    """Result from the CMSPublisher push."""
    locale: str
    platform: str
    success: bool
    cms_url: str = Field(default="")
    cms_id: str = Field(default="")
    error_message: str = Field(default="")
    published_at: str = Field(default_factory=lambda: datetime.utcnow().isoformat())


class PipelineResult(BaseModel):
    """Complete pipeline result for a single product."""
    product_name: str
    profile: dict = Field(default_factory=dict)
    storyline: dict = Field(default_factory=dict)
    localized: list[dict] = Field(default_factory=list)
    reviews: list[dict] = Field(default_factory=list)
    published: list[dict] = Field(default_factory=list)
    errors: list[str] = Field(default_factory=list)
    total_time_seconds: float = 0.0
    completed_at: str = Field(default_factory=lambda: datetime.utcnow().isoformat())
